### ISSUE TITLE
WD query optimisations

### ISSUE THREAD

**Issue by generalist** [SimonXIX/wikiheist#1]
Looking at `wikiheist/web/app/__init__.py`, a couple of little optimisations:

* If you're doing the query on the WD query server, you don't need the PREFIX lines
* `FILTER(EXISTS { ?person wdt:P18 ?o. })` - the main query already requires the item have a P18 claim, so this won't really do anything
* `FILTER(NOT EXISTS { ?person (wdt:P570|wdt:P509|wdt:P20) ?o. })` - I think (broadly speaking) there are virtually no items with a P509 or P20 that do not also have a P570, so you can simplify this line to something like `FILTER NOT EXISTS { ?person wdt:P570 ?o. }`

The big optimisation is labels - essentially, it's currently searching for everyone who meets the requirement (about 22k people), finding the labels for all of them, and then picking six.

The best way to do this is to run an inner and outer query [like this](https://query.wikidata.org/#SELECT%20%3Fperson%20%3FpersonLabel%20%3FpersonDescription%20%3Fimage%20WHERE%20%7B%0A%20%20%7B%20SELECT%20%3Fperson%20%3Fimage%20WHERE%20%7B%0A%20%20%20%20%3Fperson%20wdt%3AP31%20wd%3AQ5%3B%0A%20%20%20%20%20%20wdt%3AP27%20wd%3AQ145%3B%0A%20%20%20%20%20%20wdt%3AP569%20%3Fbirth%3B%0A%20%20%20%20%20%20wdt%3AP18%20%3Fimage.%0A%20%20%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%20%3Fperson%20wdt%3AP570%20%3Fo.%20%7D%20%0A%20%20%20%20%20%20FILTER%28%3Fbirth%20%3E%3D%20%221922-01-01%22%5E%5Exsd%3AdateTime%29%0A%20%20%20%7D%20LIMIT%206%20%20%7D%0A%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%0AORDER%20BY%20%28UUID%28%29%29) - the inner query finds six people who fit the requirements, and then the outer query takes _only_ those six and looks up the labels for them. It brings it down to about five seconds.

**Comment by generalist** [comment]
For the art query, you can do the same trick (inner query to find the artwork, outer query to find the labels) - you'll get a similar speeding up - and also simplify `  OPTIONAL { ?art wdt:P18 ?image. }  FILTER(EXISTS { ?art wdt:P18 ?o. })` into a single `?art wdt:P18 ?image . ` 

The artwork will only get things explicitly identified as "work of art" which is relatively rare (~9k items with images) - while all people are P31:Q5, for most things it's more common to use a specific subclass here, eg the Venus de Milo is "instance of: statue", statue is subclass of sculpture, which is subclass of visual artwork, which is subclass of work of art. If you wanted to get "an instance of any kind of visual artwork", then you could use something like `?art wdt:P31 ?class . ?class wd:P279* wd:Q4502142` (the asterisk means it will go down the subclass chain)

**Comment by SimonXIX** [comment]
Thanks @generalist! The inner query / outer query structure makes quite a big difference to the speed. I've implemented quite a few of these suggestions and it's working a lot better.
